from pathlib import Path
import re, json

p=Path('index.html')
s=p.read_text(encoding='utf-8')

# Premium UI CSS
css=r'''
/* Premium 3D Word Scoop UI */
:root{--bg:#f3f5ff;--card:#fff;--ink:#17172b;--muted:#70748c;--line:#e5e7f4;--brand:#5b4bff;--brand2:#8b5cf6;--lime:#c7ff54;--soft:#efefff;--ok:#16804b;--bad:#c0394b}
body{background:radial-gradient(circle at 10% 0%,rgba(139,92,246,.13),transparent 28rem),radial-gradient(circle at 95% 10%,rgba(199,255,84,.18),transparent 25rem),var(--bg);perspective:1400px}.shell{max-width:1240px;padding-top:22px}
.hero-dashboard{position:relative;display:grid;grid-template-columns:minmax(0,1.6fr) minmax(260px,.75fr);gap:22px;padding:30px 30px 112px;min-height:560px;background:radial-gradient(circle at 88% 18%,rgba(104,85,255,.34),transparent 30%),linear-gradient(135deg,#161633 0%,#28215f 55%,#4f3be7 100%);border-radius:34px;overflow:hidden;color:white;box-shadow:0 16px 0 #231b67,0 30px 70px rgba(41,32,130,.26)}
.hero-dashboard:before{content:"";position:absolute;inset:14px;border:1px solid rgba(255,255,255,.08);border-radius:25px;pointer-events:none}.hero-copy{position:relative;z-index:2}.hero-dashboard .eyebrow{color:var(--lime)}.hero-dashboard h1{font-size:clamp(38px,5vw,68px);max-width:760px;margin:10px 0 8px;line-height:.96}.hero-dashboard .sub{font-size:18px;color:#d8d6f2}
.hero-statgrid{display:grid;grid-template-columns:1fr 1fr;gap:14px;margin-top:26px;max-width:690px}.hero-stat{min-height:100px;padding:18px;border-radius:22px;display:flex;align-items:center;gap:15px;border:1px solid rgba(255,255,255,.2);box-shadow:inset 0 1px 0 rgba(255,255,255,.18),0 7px 0 rgba(15,11,55,.25),0 13px 26px rgba(8,7,32,.16)}.hero-stat.purple{background:linear-gradient(135deg,rgba(115,91,255,.48),rgba(108,74,238,.38))}.hero-stat.teal{background:linear-gradient(135deg,rgba(44,191,183,.40),rgba(76,133,205,.35))}.hero-stat.coral{background:linear-gradient(135deg,rgba(236,100,126,.42),rgba(172,84,139,.34))}.hero-stat.gold{background:linear-gradient(135deg,rgba(219,164,72,.46),rgba(142,106,72,.34))}.hero-stat.violet{background:linear-gradient(135deg,rgba(115,91,255,.42),rgba(89,72,173,.34))}.hero-stat .num{font-size:30px;color:#fff}.hero-stat .label{color:#ecebff}.hero-icon{width:54px;height:54px;display:grid;place-items:center;border-radius:17px;font-size:24px;font-weight:1000;background:linear-gradient(145deg,rgba(255,255,255,.28),rgba(255,255,255,.10));border:1px solid rgba(255,255,255,.22);box-shadow:0 5px 0 rgba(18,14,65,.20),0 10px 20px rgba(8,7,35,.18)}
.hero-visual{position:relative;z-index:2;display:flex;align-items:center;justify-content:center;min-height:370px}.abc-stage{position:relative;width:300px;height:300px;border-radius:34px;background:linear-gradient(145deg,#6351ff,#2d256a);box-shadow:0 16px 0 #251d66,0 30px 50px rgba(20,14,80,.35);transform:rotate(-2deg)}.abc-book{position:absolute;left:45px;right:45px;bottom:55px;height:72px;border-radius:16px;background:linear-gradient(180deg,#fff,#dcd8ff);box-shadow:0 10px 0 #8f84ff,0 18px 26px rgba(25,18,90,.28)}.abc-letter{position:absolute;font-weight:1000;font-size:96px;line-height:1;text-shadow:0 8px 0 rgba(23,17,78,.22),0 16px 30px rgba(23,17,78,.24)}.abc-a{left:30px;top:80px;color:#5ea8ff;transform:rotate(-9deg)}.abc-b{left:108px;top:34px;color:#a177ff}.abc-c{right:17px;top:104px;color:#78e08f;transform:rotate(10deg)}.abc-star{position:absolute;right:26px;top:25px;color:#ffd35a;font-size:44px;filter:drop-shadow(0 7px 5px rgba(80,50,0,.25))}.hero-note{position:absolute;right:5%;top:5%;font-family:cursive;font-size:24px;line-height:1.05;color:#aaa2ff;transform:rotate(-5deg);text-align:center}
.continue-hero{position:absolute;left:30px;right:30px;bottom:24px;z-index:3;height:72px;border:0;border-radius:24px;display:flex;align-items:center;gap:16px;padding:0 18px;color:white;text-align:left;background:linear-gradient(90deg,#6c55ff,#7a59ff 58%,#8b6cff);box-shadow:0 8px 0 #4f3ccf,0 16px 30px rgba(61,45,180,.28);cursor:pointer}.continue-hero b{display:block;font-size:22px}.continue-hero small{display:block;color:#e9e6ff;margin-top:2px;font-size:13px}.play3d,.go3d{width:48px;height:48px;border-radius:50%;display:grid;place-items:center;background:rgba(255,255,255,.18);border:1px solid rgba(255,255,255,.2);box-shadow:0 4px 0 rgba(48,35,148,.35)}.go3d{margin-left:auto;font-size:32px}
.topbar{background:#fff;border:1px solid var(--line);padding:12px;border-radius:20px;box-shadow:0 7px 0 #e1e4ef,0 15px 28px rgba(39,36,91,.08)}.btn{background:var(--brand);box-shadow:0 6px 0 #3f32c8,0 10px 18px rgba(55,44,170,.18);transition:.18s transform,.18s box-shadow}.btn:hover{transform:translateY(-2px);box-shadow:0 8px 0 #3f32c8,0 14px 22px rgba(55,44,170,.20)}.btn:active{transform:translateY(3px);box-shadow:0 2px 0 #3f32c8}.btn.secondary{box-shadow:0 5px 0 #d9dcea,0 10px 18px rgba(45,42,88,.08);background:#fff}.actionbar{display:grid;grid-template-columns:repeat(3,1fr);gap:10px}.actionbar .btn{min-height:54px;text-decoration:none;display:flex;align-items:center;justify-content:center}
.premium-dashboard{display:grid;grid-template-columns:1.55fr .8fr;gap:14px;margin:18px 0}.premium-main{min-height:230px;padding:28px;border-radius:30px;background:linear-gradient(145deg,#17172b,#30266c 62%,#5b4bff);color:#fff;position:relative;overflow:hidden;box-shadow:0 12px 0 #211a61,0 26px 52px rgba(40,31,130,.22)}.premium-main .tag{background:var(--lime);color:#17172b}.premium-main h2{font-size:clamp(30px,4vw,48px);margin:14px 0 6px;line-height:1}.premium-side{display:grid;grid-template-columns:1fr 1fr;gap:12px}.metric3d{background:#fff;border:1px solid var(--line);border-radius:24px;padding:18px;box-shadow:0 7px 0 #e4e5f1,0 14px 25px rgba(35,31,83,.08)}.metric3d .v{font-size:30px;font-weight:1000;margin-top:10px}.metric3d .k{font-size:11px;font-weight:900;letter-spacing:.08em;color:var(--muted)}
.section-title{display:flex;align-items:center;gap:10px}.section-title:before{content:"";width:12px;height:28px;border-radius:999px;background:linear-gradient(var(--brand),var(--brand2))}.journey{display:grid;gap:18px}.zone{position:relative;padding:20px;border-radius:30px;background:rgba(255,255,255,.78);border:1px solid rgba(217,218,237,.9);box-shadow:0 8px 0 rgba(219,220,237,.8),0 16px 35px rgba(39,36,91,.06);backdrop-filter:blur(10px)}.zonehead{display:flex;justify-content:space-between;align-items:center;gap:10px;margin-bottom:16px}.zonetitle{font-size:20px;font-weight:1000}.zonesub{font-size:12px;color:var(--muted);font-weight:800}.zonegrid{display:grid;grid-template-columns:repeat(3,1fr);gap:12px}.card{transform-style:preserve-3d;box-shadow:0 8px 0 rgba(33,30,78,.10),0 16px 30px rgba(39,35,95,.10);border-radius:24px}.card:hover{transform:translateY(-5px) rotateX(1deg);box-shadow:0 12px 0 rgba(48,40,120,.15),0 24px 48px rgba(39,35,95,.14)}.progress{height:10px}.bar{background:linear-gradient(90deg,var(--brand),var(--brand2))}.zoneboss{margin-top:14px;border:1px dashed #aaa2ff;border-radius:20px;padding:16px;background:linear-gradient(135deg,#f7f5ff,#eeebff);font-weight:900}.vocab-download-card{margin:18px 0;background:linear-gradient(135deg,#fff,#f5f3ff);border:1px solid #ddd9ff}.vocab-download-card .btn{display:inline-block;text-decoration:none;margin-top:8px}
.quizbox{border-radius:24px;background:#f8f8ff;box-shadow:inset 0 1px 0 #fff,0 7px 0 #e6e7f4,0 15px 30px rgba(39,36,91,.08)}.quizbox input{font-size:20px;padding:15px 16px;width:100%;border:2px solid #ddd9ff}.quizbox input:focus{outline:none;border-color:var(--brand);box-shadow:0 0 0 5px rgba(91,75,255,.10)}.feedback.ok{animation:correctPop .3s ease}.feedback.bad{animation:wrongShake .28s ease}@keyframes correctPop{50%{transform:scale(1.035)}}@keyframes wrongShake{25%{transform:translateX(-5px)}50%{transform:translateX(5px)}75%{transform:translateX(-3px)}}
@media(max-width:900px){.hero-dashboard{grid-template-columns:1fr;padding-bottom:112px}.hero-visual{display:none}.hero-statgrid{max-width:none}.premium-dashboard{grid-template-columns:1fr}.zonegrid{grid-template-columns:1fr 1fr}}@media(max-width:560px){.hero-dashboard{padding:24px 18px 104px;min-height:auto}.hero-statgrid,.premium-side,.zonegrid,.actionbar{grid-template-columns:1fr}.continue-hero{left:18px;right:18px;bottom:18px}}
'''
if 'Premium 3D Word Scoop UI' not in s:
    s=s.replace('</style>',css+'\n</style>',1)

# Hero redesign, keeping all live progress IDs
hero='''<div class="hero hero-dashboard"><div class="hero-copy"><div class="eyebrow">YEAR 5 · WORD SCOOP</div><h1>Scoop Up Your Spelling</h1><div class="sub">Your vocabulary adventure · 24 themes · 192 words</div><div class="hero-statgrid"><div class="hero-stat purple"><div class="hero-icon">▰</div><div><div class="num" id="sThemes">0/24</div><div class="label">Themes completed</div></div></div><div class="hero-stat teal"><div class="hero-icon">✓</div><div><div class="num" id="sWords">0/192</div><div class="label">Words mastered</div></div></div><div class="hero-stat coral"><div class="hero-icon">↻</div><div><div class="num" id="sRevise">0</div><div class="label">Words to revise</div></div></div><div class="hero-stat gold"><div class="hero-icon">★</div><div><div class="num" id="sCoins">0</div><div class="label">Coins</div></div></div><div class="hero-stat violet"><div class="hero-icon">▥</div><div><div class="num" id="sAverage">—</div><div class="label">Average score</div></div></div></div></div><div class="hero-visual"><div class="abc-stage"><div class="abc-star">★</div><div class="abc-letter abc-a">A</div><div class="abc-letter abc-b">B</div><div class="abc-letter abc-c">C</div><div class="abc-book"></div></div><div class="hero-note">Small Steps<br>Big Progress!</div></div><button class="continue-hero" onclick="document.querySelector('#lobbyBento .premium-main .btn')?.click()"><span class="play3d">▶</span><span><b>Continue Learning</b><small>Pick up where you left off</small></span><span class="go3d">›</span></button></div>'''
s=re.sub(r'<div class="hero">.*?</div>\s*<div class="topbar">',hero+'\n<div class="topbar">',s,count=1,flags=re.S)

# PDF controls and dashboard/journey containers
if 'Download Vocabulary PDF' not in s:
    s=s.replace('<div class="actionbar">','<div class="actionbar"><a class="btn secondary" href="Year5_Word_Scoop_Vocabulary.pdf" download>Download Vocabulary PDF</a>',1)
if 'id="lobbyBento"' not in s:
    s=s.replace('<h2 class="section-title">Themes</h2><div class="grid" id="themeGrid"></div>','<div id="lobbyBento" class="premium-dashboard"></div><div class="card vocab-download-card"><div class="tag">VOCABULARY BOOKLET</div><h3>192-Word Vocabulary PDF</h3><p class="words">24 themes with English words, Chinese meanings and English clues. Suitable for revision or printing.</p><a class="btn" href="Year5_Word_Scoop_Vocabulary.pdf" download>Download PDF</a></div><h2 class="section-title">Learning Journey</h2><div class="journey" id="themeGrid"></div>',1)
else:
    s=s.replace('<h2 class="section-title">Themes</h2>','<h2 class="section-title">Learning Journey</h2>')

# Lobby renderer
lobby=r'''function renderLobby(){const box=document.getElementById('lobbyBento');if(!box)return;let next=0;for(let i=0;i<THEMES.length;i++){if(!themeComplete(i)){next=i;break}else next=Math.min(i+1,23)}const t=THEMES[next],m=modeState(next),done=['learn','definition','spell','exam'].filter(k=>m[k]).length,pct=Math.round(done/4*100);const rev=Object.keys(state.revise).length,avg=averageScore(),complete=THEMES.filter((_,i)=>themeComplete(i)).length;box.innerHTML=`<div class="premium-main"><div class="tag">CONTINUE JOURNEY</div><h2>${state.student?`Welcome back, ${state.student}`:'Ready for your next mission?'}</h2><p style="color:#dcd9ff;font-size:16px">Theme ${next+1} · ${t.name} · ${pct}% complete</p><div class="progress" style="background:rgba(255,255,255,.16);max-width:620px"><div class="bar" style="width:${pct}%;background:#c7ff54"></div></div><button class="btn" style="margin-top:16px;background:#fff;color:#332a8c;box-shadow:0 6px 0 #d9d5ff" onclick="openTheme(${next})">Continue Mission</button></div><div class="premium-side"><div class="metric3d"><div class="k">THEMES</div><div class="v">${complete}/24</div><div class="words">Journey progress</div></div><div class="metric3d"><div class="k">AVERAGE</div><div class="v">${avg===null?'—':avg+'%'}</div><div class="words">Best scores</div></div><div class="metric3d"><div class="k">REVISION</div><div class="v">${rev}</div><button class="btn secondary" onclick="openReviseAll()">Revise</button></div><div class="metric3d"><div class="k">COINS</div><div class="v">${state.coins}</div><button class="btn secondary" onclick="showHome()">My Home</button></div></div>`;}'''
if 'function renderLobby()' not in s:
    s=s.replace('function render(){',lobby+'\nfunction render(){',1)

# Replace simple theme grid inside render() with four-zone journey
start=s.find("const grid=document.getElementById('themeGrid');")
end=s.find("const cp=document.getElementById('checkpointGrid');",start)
if start!=-1 and end!=-1:
    zone=r'''const grid=document.getElementById('themeGrid');grid.innerHTML='';for(let z=0;z<4;z++){const from=z*6,to=from+6;const completed=Array.from({length:6},(_,k)=>themeComplete(from+k)).filter(Boolean).length;const zone=document.createElement('section');zone.className='zone';zone.innerHTML=`<div class="zonehead"><div><div class="zonetitle">Zone ${z+1}</div><div class="zonesub">Themes ${from+1}–${to} · ${completed}/6 completed</div></div><div class="chip">${Math.round(completed/6*100)}%</div></div><div class="zonegrid"></div>`;const zg=zone.querySelector('.zonegrid');for(let i=from;i<to;i++){const t=THEMES[i],m=modeState(i),done=['learn','definition','spell','exam'].filter(k=>m[k]).length,pct=Math.round(done/4*100);const c=document.createElement('div');c.className='card';c.innerHTML=`<div class="tag">MISSION ${i+1}</div><h3>${t.name}</h3><div class="words">${t.words.slice(0,4).map(x=>x.word).join(' · ')}...</div><div class="modechips"><span class="modechip ${m.learn?'done':''}">Learn ${m.learn?'✓':''}</span><span class="modechip ${m.definition?'done':''}">Definition ${m.definition?'✓':''}</span><span class="modechip ${m.spell?'done':''}">Spelling ${m.spell?'✓':''}</span><span class="modechip ${m.exam?'done':''}">Exam ${m.exam?'✓':''}</span></div><div class="progress"><div class="bar" style="width:${pct}%"></div></div><button class="btn" onclick="openTheme(${i})">${themeComplete(i)?'Replay Theme':'Start Mission'}</button> <button class="btn secondary" onclick="openTheme(${i});setTimeout(()=>startQuiz('exam'),50)">Quick Exam</button>`;zg.appendChild(c)}const passed=!!state.badges[z],unlocked=Array.from({length:6},(_,k)=>themeComplete(from+k)).every(Boolean);const boss=document.createElement('div');boss.className='zoneboss';boss.innerHTML=`Boss Gate ${z+1} · ${passed?'Cleared':unlocked?'Ready':'Locked until all 6 missions are complete'}`;zone.appendChild(boss);grid.appendChild(zone)}renderLobby();'''
    s=s[:start]+zone+s[end:]

p.write_text(s,encoding='utf-8')

# Build the vocabulary PDF from the same 24-theme data
m=re.search(r'const THEMES\s*=\s*(\[.*?\]);\s*const ',s,re.S) or re.search(r'const THEMES\s*=\s*(\[.*?\]);',s,re.S)
themes=json.loads(m.group(1))
from reportlab.lib.pagesizes import A4
from reportlab.platypus import SimpleDocTemplate,Paragraph,Spacer,Table,TableStyle,PageBreak
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet,ParagraphStyle
from reportlab.lib.enums import TA_CENTER
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.cidfonts import UnicodeCIDFont
pdfmetrics.registerFont(UnicodeCIDFont('STSong-Light'))
font='STSong-Light'; out='Year5_Word_Scoop_Vocabulary.pdf'
doc=SimpleDocTemplate(out,pagesize=A4,rightMargin=28,leftMargin=28,topMargin=28,bottomMargin=28)
st=getSampleStyleSheet(); title=ParagraphStyle('t',parent=st['Title'],fontName=font,fontSize=23,leading=28,textColor=colors.HexColor('#221B57'),alignment=TA_CENTER,spaceAfter=4); sub=ParagraphStyle('s',parent=st['Normal'],fontName=font,fontSize=9.5,leading=13,textColor=colors.HexColor('#67627F'),alignment=TA_CENTER,spaceAfter=12); th=ParagraphStyle('th',parent=st['Heading2'],fontName=font,fontSize=13,leading=16,textColor=colors.white); cell=ParagraphStyle('c',parent=st['Normal'],fontName=font,fontSize=8.2,leading=10.4,textColor=colors.HexColor('#232338')); small=ParagraphStyle('sm',parent=cell,fontSize=7.6,leading=9.4,textColor=colors.HexColor('#55536A'))
story=[Paragraph('Year 5 Word Scoop',title),Paragraph('Vocabulary Reference - 24 Themes - 192 Words',sub)]
for ti,t in enumerate(themes):
    band=Table([[Paragraph(f"Theme {ti+1} - {t['name']}",th)]],colWidths=[A4[0]-56]);band.setStyle(TableStyle([('BACKGROUND',(0,0),(-1,-1),colors.HexColor('#5B4BFF')),('LEFTPADDING',(0,0),(-1,-1),10),('RIGHTPADDING',(0,0),(-1,-1),10),('TOPPADDING',(0,0),(-1,-1),6),('BOTTOMPADDING',(0,0),(-1,-1),6)]))
    data=[[Paragraph('Word',cell),Paragraph('中文',cell),Paragraph('English clue',cell)]]+[[Paragraph(w['word'],cell),Paragraph(w['meaning'],cell),Paragraph(w['definition'],small)] for w in t['words']]
    tbl=Table(data,colWidths=[120,88,A4[0]-56-208],repeatRows=1);tbl.setStyle(TableStyle([('BACKGROUND',(0,0),(-1,0),colors.HexColor('#EFEFFF')),('GRID',(0,0),(-1,-1),.35,colors.HexColor('#DDDDF0')),('VALIGN',(0,0),(-1,-1),'MIDDLE'),('LEFTPADDING',(0,0),(-1,-1),6),('RIGHTPADDING',(0,0),(-1,-1),6),('TOPPADDING',(0,0),(-1,-1),4.2),('BOTTOMPADDING',(0,0),(-1,-1),4.2),('ROWBACKGROUNDS',(0,1),(-1,-1),[colors.white,colors.HexColor('#FBFBFF')])]))
    story += [band,Spacer(1,5),tbl,Spacer(1,12)]
    if ti%2==1 and ti!=len(themes)-1: story.append(PageBreak())
def footer(c,d):
    c.saveState();c.setFont(font,7.5);c.setFillColor(colors.HexColor('#85829B'));c.drawString(28,14,'Year 5 Word Scoop - Vocabulary Reference');c.drawRightString(A4[0]-28,14,f'Page {d.page}');c.restoreState()
doc.build(story,onFirstPage=footer,onLaterPages=footer)
print('updated index.html and generated PDF')
